workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60

    environment:
      xcode: latest

    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install

      - name: Build iOS app
        script: |
          xcodebuild \
          -workspace "src/Catalogue BIO PLANTES.xcworkspace" \
          -scheme "Catalogue BIO PLANTES" \
          -sdk iphoneos \
          -configuration Release \
          archive \
          -archivePath $CM_BUILD_DIR/build/CatalogueBIOPLANTES.xcarchive

    artifacts:
      - build/**/*.ipa